config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  resources :friends
  # get 'home/index'
  
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
   # @friend = Friend.new(friend_params)
   @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend =current_user.friends.find_by(id: params[:id])
    redirect_to friends_path,notice: "Not authorised to Edit" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.text_field :first_name, class:"form-control",placeholder:"First Name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :last_name, class:"form-control",placeholder:"Last Name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :email, class:"form-control" ,placeholder:"Email"%>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :phone, class:"form-control",placeholder:"Phone Number" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :twitter, class:"form-control",placeholder:"Twitter Username" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control",value:current_user.id, type:"hidden"%>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="card border-success bg-light text-dark mx-auto" style="width: 50%;">

<div class="card-header">
<h2 class="text-center">Editing friend</h2>
</div>

<div class="card-body">

<%= render "form", friend: @friend %>

<br/>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>
</div>
</div>

app/views/friends/index.html.erb
<div class="card border-dark bg-info text-white mx-auto">

  <div class="card-header">
  <h1 class="text-center"> My Friends</h1>
  </div>
  
  <div class="card-body">


<div id="friends">
<table class="table table-secondary table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Mobile</th>
      <th scope="col">Twitter Handle</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend|%>
    <%if friend.user == current_user%>
    <tr>
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
    <td><%= link_to "Display", friend %></td>
    </tr>
    <% end %>
    <% end %>
    </tbody>
    </table>
</div>

<%= link_to "New friend", new_friend_path, class:'btn btn-secondary' %>
</div>
</div>

app/views/friends/new.html.erb
<div class="card border-success bg-light text-dark mx-auto" style="width: 30rem;">

<div class="card-header">
<h2 class="text-center">New friend</h2>
</div>

<div class="card-body">
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:'btn btn-dark' %>
</div>
</div>
</div>

app/views/friends/show.html.erb
<div class="card border-success bg-secondary text-white mx-auto" style="width: 60rem;">

  <div class="card-header">
  <h1 class="display-4"><strong>Name:</strong> <%= @friend.first_name + " " + @friend.last_name%></h1>
  </div>

  <div class="card-body">
  <p class="lead"><strong>Email:</strong> <%= @friend.email%></p>
 
  <p><strong>Phone:</strong> <%= @friend.phone%></p>
  <p><strong>Twitter Handle:</strong> <%= @friend.email%></p>
  <%= link_to "Edit", edit_friend_path(@friend), class:'btn btn-primary ' %> |
  <%= link_to "Back", friends_path, class:'btn  btn-dark'%> | 
  <%= link_to "Delete", @friend, method: :delete, class:'btn btn-danger'%>
</div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger text-dark">
<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <li class="nav-item">
      <%= link_to 'About Us', home_about_path, class:'nav-link' %>
      </li>

        <% if user_signed_in?%>
        <li class="nav-item">
        <%= link_to 'Friends', friends_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>

        <% else %>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
        </li>
        <% end %>

       
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1 class="text-white">About Us Page</h1>

app/views/home/index.html.erb
<div>
<img src="../assets/images/logo.png" alt="logo">
<div class="container-fluid text-center">
<h1 class="text-white text-center h1-index">Welcome To Friends APP-We Help You Keep a Back Up Of Friends Social Data</h1>
<% if user_signed_in?%>
<h1 class="blink text-info">HAVE FUN!</h1>
<% else %>
<%= link_to 'Get Started', new_user_session_path, class:'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
 <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
   <br>
  <% if notice %>
  <%= render 'layouts/alerts' %>
  <% end %>

    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
  </body>
</html>